#
# Tasks: Install Remote Packages
#


- name: Install remote packages
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items:
    - "{{ remote_packages }}"
